<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function islandora_mirador_bookreader_menu() {
  return array(
    'admin/islandora/islandora_viewers/mirador_bookreader' => array(
      'title' => 'Mirador BookReader',
      'description' => 'Configure the Mirador BookReader.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_mirador_bookreader_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    'admin/islandora/islandora_viewers/mirador_bookreader/config' => array(
      'title' => 'Mirador BookReader Configuration',
      'description' => 'Configure the Mirador BookReader.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_mirador_bookreader_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => 0,
    ),
    'admin/islandora/islandora_viewers/mirador_bookreader/json_generate' => array(
      'title' => 'JSON for IIIF manifest',
      'description' => 'JSON file for IIIF manifest',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_mirador_bookreader_generate_json_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => 1,
    ),

  );
}

/**
 * Implements hook_theme().
 */
function islandora_mirador_bookreader_theme() {
  return array(
    'islandora_mirador_bookreader' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-mirador-bookreader',
      'variables' => array(
        'object' => NULL,
        'datastream_id' => 'JP2',
        'page_progression' => 'rl',
        'pages' => array(),
      ),
    ),
    'islandora_mirador_bookreader_book_info' => array(
      'file' => 'theme/theme.inc',
      'variables' => array('object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_mirador_bookreader_islandora_viewer_info() {
  return array(
    'islandora_mirador_bookreader' => array(
      'label' => t('Mirador BookReader'),
      'description' => t('Mirador BookReader.'),
      'configuration' => 'admin/islandora/islandora_viewers/mirador_bookreader',
      'callback' => 'islandora_mirador_bookreader_viewer_callback',
      'model' => array(
        'islandora:bookCModel',
        'islandora:newspaperIssueCModel',
        'islandora:manuscriptCModel',
        'islandora:sp_basic_image',
        'islandora:sp_large_image_cmodel',
        'islandora:compoundCModel'
      ),
      'mimetype' => array('image/jp2')
    ),
  );
}

function islandora_mirador_bookreader_viewer_callback(array $params) {
  return theme('islandora_mirador_bookreader', $params);
}
